"use client";
import "cropperjs/dist/cropper.css";

import React, {
  useEffect,
  useMemo,
  useState,
  useRef,
  ChangeEvent,
} from "react";
import { useRouter } from "next/navigation";
import axios from "axios";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import Cropper, { ReactCropperElement } from "react-cropper";
import { useAuth } from "../components/AuthProvider";

const API_BASE = "https://webapi.ceflix.org/api/";
const APP_KEY = "2567a5ec9705eb7ac2c984033e06189d";

const DRAFT_KEY = "ceflix_upload_wizard_draft_v1";

const privacyTypes2 = [
  {
    id: 1,
    title: "public",
    description: "Anyone can search for and view",
    current: true,
  },
  {
    id: 0,
    title: "private",
    description: "Only you can view",
    current: false,
  },
];

type Channel = {
  id: number;
  channel: string;
};

type Category = {
  id: number;
  title: string;
};

const steps = [
  { id: 1, key: "details", label: "Details" },
  { id: 2, key: "branding", label: "Branding" },
  { id: 3, key: "visibility", label: "Visibility" },
];

export default function UploadPage() {
  const router = useRouter();
  const { token, user } = useAuth();

  const isLoggedIn = !!user && !!token;

  const [loading, setLoading] = useState(true);

  // wizard step
  const [step, setStep] = useState(1);

  // upload type: 0 = file, 1 = stream
  const [select, setSelect] = useState<0 | 1>(0);

  // channel / categories
  const [channels, setChannels] = useState<Channel[]>([]);
  const [channelId, setChannelId] = useState<string>("");
  const [categories, setCategories] = useState<Category[]>([]);
  const [categoryId, setCategoryId] = useState<string>("");

  // details
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [tags, setTags] = useState("");
  const [isShort, setIsShort] = useState<"yes" | "no">("no");
  // privacy
  const [privacyVal, setPrivacyVal] = useState(privacyTypes2[0]);
  const [privacy, setPrivacy] = useState<string>(privacyTypes2[0].title);

  // file upload
  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [videoFileName, setVideoFileName] = useState("");

  // stream upload
  const [streamLink, setStreamLink] = useState("");
  const [datetime, setDatetime] = useState<Date>(new Date());

  // thumbnail states
  const [thumbDataUrl, setThumbDataUrl] = useState(""); // currently selected thumbnail (used for upload)
  const [thumbFileName, setThumbFileName] = useState(""); // name of uploaded thumb (if any)

  // raw image for cropper
  const [rawThumbImage, setRawThumbImage] = useState("");
  const [showCropper, setShowCropper] = useState(false);
  const cropperRef = useRef<Cropper | null>(null);

  // autogenerated thumbnails from video
  const [generatedThumbs, setGeneratedThumbs] = useState<string[]>([]);

  // upload & draft state
  const [progress, setProgress] = useState(0);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState("");

  const isSelectedDateToday = new Date().getDate() === datetime.getDate();
  const isSelectedDateInFuture = +datetime > +new Date();

  let minTimeHour = new Date().getHours();
  if (!isSelectedDateToday) minTimeHour = 0;

  const date = new Date();
  let currentMins = date.getMinutes();
  let currentHour = date.getHours();

  // ---------------------------------------------------------------------------
  // Initial setup: channels + categories + draft hydration
  // ---------------------------------------------------------------------------
  useEffect(() => {
    if (!isLoggedIn) {
      setLoading(false);
      return;
    }

    async function setup() {
      try {
        setLoading(true);

        const chReq = await fetch(API_BASE + "user/channels", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Application-Key": APP_KEY,
            "X-TOKEN": token!,
          },
          body: JSON.stringify({ token }),
        });
        const chRes = await chReq.json();

        const catReq = await fetch(API_BASE + "channelcategories", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Application-Key": APP_KEY,
            "X-TOKEN": token!,
          },
        });
        const catRes = await catReq.json();

        if (chRes.status) setChannels(chRes.data as Channel[]);
        if (catRes.status) setCategories(catRes.data as Category[]);

        let defaultChannelId =
          chRes.status && chRes.data.length > 0 ? String(chRes.data[0].id) : "";
        let defaultCategoryId =
          catRes.status && catRes.data.length > 0
            ? String(catRes.data[0].id)
            : "";

        // hydrate from draft
        const saved =
          typeof window !== "undefined"
            ? window.localStorage.getItem(DRAFT_KEY)
            : null;

        if (saved) {
          try {
            const draft = JSON.parse(saved);

            if (typeof draft.step === "number") setStep(draft.step);
            if (typeof draft.select === "number") setSelect(draft.select);

            if (draft.title) setTitle(draft.title);
            if (draft.description) setDescription(draft.description);
            if (draft.tags) setTags(draft.tags);
            if (draft.isShort === "yes" || draft.isShort === "no") {
              setIsShort(draft.isShort);
            }
            if (draft.streamLink) setStreamLink(draft.streamLink);
            if (draft.datetime) setDatetime(new Date(draft.datetime));

            if (draft.thumbDataUrl) setThumbDataUrl(draft.thumbDataUrl);
            if (draft.thumbFileName) setThumbFileName(draft.thumbFileName);

            if (draft.privacyTitle) {
              const found = privacyTypes2.find(
                (p) => p.title === draft.privacyTitle
              );
              if (found) {
                setPrivacyVal(found);
                setPrivacy(found.title);
              }
            }

            if (draft.channelId && chRes.status) {
              const chanExists = chRes.data.some(
                (c: Channel) => String(c.id) === String(draft.channelId)
              );
              if (chanExists) defaultChannelId = String(draft.channelId);
            }

            if (draft.categoryId && catRes.status) {
              const catExists = catRes.data.some(
                (c: Category) => String(c.id) === String(draft.categoryId)
              );
              if (catExists) defaultCategoryId = String(draft.categoryId);
            }
          } catch {
            // ignore malformed draft
          }
        }

        setChannelId(defaultChannelId);
        setCategoryId(defaultCategoryId);
      } catch {
        setError("Failed to load upload configuration.");
      } finally {
        setLoading(false);
      }
    }

    setup();
  }, [isLoggedIn, token]);

  // ---------------------------------------------------------------------------
  // Helpers: generate thumbnails from video file
  // ---------------------------------------------------------------------------
  const generateThumbnailsFromVideo = (file: File) => {
    try {
      const url = URL.createObjectURL(file);
      const video = document.createElement("video");
      video.src = url;
      video.crossOrigin = "anonymous";
      video.muted = true;

      video.addEventListener("loadedmetadata", () => {
        const duration = video.duration;
        if (!duration || !Number.isFinite(duration)) {
          URL.revokeObjectURL(url);
          return;
        }

        const captureTimes = [0.1, 0.3, 0.6, 0.8].map((p) =>
          Math.min(duration * p, duration - 0.1)
        );
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");
        const images: string[] = [];

        const captureAtIndex = (idx: number) => {
          if (!ctx) {
            URL.revokeObjectURL(url);
            return;
          }
          if (idx >= captureTimes.length) {
            URL.revokeObjectURL(url);
            setGeneratedThumbs(images);
            if (!thumbDataUrl && images.length > 0) {
              setThumbDataUrl(images[0]);
            }
            return;
          }

          video.currentTime = captureTimes[idx];
          video.onseeked = () => {
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
            const dataURL = canvas.toDataURL("image/jpeg", 0.8);
            images.push(dataURL);
            captureAtIndex(idx + 1);
          };
        };

        captureAtIndex(0);
      });
    } catch {
      // ignore errors – thumbnails are optional
    }
  };

  // ---------------------------------------------------------------------------
  // Handlers
  // ---------------------------------------------------------------------------
  const handleVideoChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setVideoFile(file);
    setVideoFileName(file.name);
    generateThumbnailsFromVideo(file);
  };

  const handleThumbFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setThumbFileName(file.name);

    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === "string") {
        setRawThumbImage(reader.result);
        setShowCropper(true);
      }
    };
    reader.readAsDataURL(file);
  };

  const applyCrop = () => {
    const cropper = cropperRef.current?.cropper;
    if (!cropper) return;

    const canvas = cropper.getCroppedCanvas({
      width: 1280,
      height: 720,
      imageSmoothingEnabled: true,
    });

    const dataUrl = canvas.toDataURL("image/jpeg", 0.9);
    setThumbDataUrl(dataUrl);
    setShowCropper(false);
  };

  const handlePrivacyChange = (e: ChangeEvent<HTMLSelectElement>) => {
    const val = e.target.value;
    setPrivacy(val);
    const found = privacyTypes2.find((p) => p.title === val);
    if (found) setPrivacyVal(found);
  };

  // ---------------------------------------------------------------------------
  // Draft handling
  // ---------------------------------------------------------------------------
  const saveDraft = () => {
    if (!channelId) {
      setError("Select a channel before saving a draft.");
      return;
    }

    const payload = {
      step,
      select,
      title,
      description,
      tags,
      channelId,
      categoryId,
      privacyTitle: privacyVal?.title,
      streamLink,
      datetime: datetime.toISOString(),
      thumbDataUrl,
      thumbFileName,
      isShort, // NEW
    };

    if (typeof window !== "undefined") {
      window.localStorage.setItem(DRAFT_KEY, JSON.stringify(payload));
    }
    setError("Draft saved ✔️");
    setTimeout(() => setError(""), 2000);
  };

  const clearDraft = () => {
    if (typeof window !== "undefined") {
      window.localStorage.removeItem(DRAFT_KEY);
    }
  };

  // ---------------------------------------------------------------------------
  // Upload / resume
  // ---------------------------------------------------------------------------
  const upload = () => {
    if (!token || uploading) return;

    setError("");

    if (!title || !description || !thumbDataUrl) {
      setError("Please complete title, description and thumbnail.");
      if (!title || !description) setStep(1);
      else setStep(2);
      return;
    }
    if (!channelId) {
      setError("Please select a channel.");
      setStep(2);
      return;
    }
    if (select === 0 && !videoFile) {
      setError("Please select a video file.");
      setStep(1);
      return;
    }
    if (select === 1 && (!streamLink || !datetime)) {
      setError("Please configure your stream link and end time.");
      setStep(1);
      return;
    }

    if (select === 0 && videoFile && videoFile.size / 1024 / 1024 > 1024) {
      setError("File size exceeds 1GB, please try again.");
      return;
    }

    const formData = new FormData();
    formData.append("video_title", title);
    formData.append("description", description);
    formData.append("tags", tags);
    formData.append("startDate", Math.floor(Date.now() / 1000).toString());
    formData.append("privacy", privacy);
    formData.append("token", token);
    formData.append("channel", channelId);
    formData.append("thumbnail", thumbDataUrl);
    formData.append("is_short", isShort);
    if (select === 0 && videoFile) {
      formData.append("type", "video");
      formData.append("file", videoFile);
    }
    if (select === 1) {
      formData.append("type", "stream");
      formData.append("stream", streamLink);
      formData.append(
        "endDate",
        Math.floor(datetime.getTime() / 1000).toString()
      );
    }

    setUploading(true);

    axios
      .post(API_BASE + "video/upload", formData, {
        headers: {
          "Application-Key": APP_KEY,
          "X-TOKEN": token,
        },
        onUploadProgress: (event) => {
          if (!event.total) return;
          const percent = Math.round((event.loaded * 100) / event.total);
          setProgress(percent);
        },
      })
      .then((response) => {
        if (response.status) {
          clearDraft();
          router.replace(`/channel/${channelId}`);
        } else {
          setError("Upload failed, please try again.");
        }
      })
      .catch(() => {
        setError(
          "Network error. You can click the button again to resume the upload."
        );
      })
      .finally(() => {
        setUploading(false);
      });
  };

  const uploadButtonLabel = useMemo(() => {
    if (uploading) return "Uploading…";
    if (progress > 0 && progress < 100) return "Resume upload";
    if (progress === 100) return "Re-upload";
    return "Publish";
  }, [uploading, progress]);

  const nextStep = () => {
    if (step < 3) setStep(step + 1);
  };
  const prevStep = () => {
    if (step > 1) setStep(step - 1);
  };

  const selectedChannel = channels.find(
    (c) => String(c.id) === String(channelId)
  );

  // ---------------------------------------------------------------------------
  // Not logged in
  // ---------------------------------------------------------------------------
  if (!isLoggedIn) {
    return (
      <main className="min-h-screen bg-neutral-950 text-white">
        <div className="max-w-6xl mx-auto px-4 sm:px-8 pt-24 pb-10">
          <h1 className="text-3xl font-extrabold mb-3">Upload</h1>
          <p className="text-neutral-400 text-sm mb-4">
            Sign in to upload videos to your channels.
          </p>
          <button
            type="button"
            onClick={() => router.push("/login")}
            className="cursor-pointer rounded-full bg-white px-5 py-2 text-sm font-semibold text-black hover:bg-neutral-200 transition"
          >
            Sign in
          </button>
        </div>
      </main>
    );
  }

  // ---------------------------------------------------------------------------
  // Loading skeleton
  // ---------------------------------------------------------------------------
  if (loading) {
    return (
      <main className="min-h-screen bg-neutral-950 text-white">
        <div className="max-w-6xl mx-auto px-4 sm:px-8 pt-16 pb-10">
          <div className="animate-pulse space-y-6">
            <div className="h-7 w-40 bg-neutral-800 rounded" />
            <div className="h-10 w-full bg-neutral-800 rounded" />
            <div className="h-64 bg-neutral-900 rounded" />
          </div>
        </div>
      </main>
    );
  }

  // ---------------------------------------------------------------------------
  // No channel yet
  // ---------------------------------------------------------------------------
  if (!loading && channels.length === 0) {
    return (
      <main className="min-h-screen bg-neutral-950 text-white">
        <div className="flex flex-col items-center justify-center max-w-6xl mx-auto px-4 sm:px-8 pt-24 pb-10">
          <h1 className="text-2xl font-semibold mb-3 text-center">
            To upload to Ceflix, please create a channel
          </h1>
          <button
            type="button"
            onClick={() => router.push("/studio/channels")}
            className="cursor-pointer mt-2 text-sm whitespace-nowrap items-center gap-x-2 text-white font-bold transition bg-red-700 hover:bg-red-600 px-4 py-2 rounded-full"
          >
            Create Channel
          </button>
        </div>
      </main>
    );
  }

  // ---------------------------------------------------------------------------
  // Main UI (YouTube-style wizard)
  // ---------------------------------------------------------------------------
  return (
    <main className="min-h-screen bg-neutral-950 text-white">
      <div className="max-w-6xl mx-auto px-4 sm:px-8 pt-8 pb-28">
        {/* top bar: title + save draft */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <h1 className="text-xl sm:text-2xl font-semibold">
              {title || "New video"}
            </h1>
            {privacy && (
              <span className="text-xs rounded-full border border-neutral-600 px-2 py-0.5 text-neutral-300">
                {privacy === "public" ? "Public" : "Private"}
              </span>
            )}
          </div>

          <button
            type="button"
            onClick={saveDraft}
            className="cursor-pointer text-sm px-3 py-1 rounded-full bg-neutral-800 hover:bg-neutral-700"
          >
            Save draft
          </button>
        </div>

        {/* stepper like YouTube */}
        <div className="flex items-center gap-4 mb-8">
          {steps.map((s, idx) => {
            const active = step === s.id;
            const completed = step > s.id;
            return (
              <React.Fragment key={s.id}>
                <div className="flex items-center gap-2">
                  <div
                    className={`h-7 w-7 flex items-center justify-center rounded-full text-sm font-semibold ${
                      active
                        ? "bg-white text-black"
                        : completed
                        ? "bg-red-600 text-white"
                        : "bg-neutral-800 text-neutral-300"
                    }`}
                  >
                    {s.id}
                  </div>
                  <span
                    className={`text-sm sm:text-sm ${
                      active ? "text-white font-semibold" : "text-neutral-400"
                    }`}
                  >
                    {s.label}
                  </span>
                </div>
                {idx < steps.length - 1 && (
                  <div className="flex-1 h-px bg-neutral-700/60" />
                )}
              </React.Fragment>
            );
          })}
        </div>

        {/* two-column layout like screenshot */}
        <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,2.2fr)_minmax(260px,1fr)] gap-6">
          {/* LEFT: main card */}
          <section className="rounded-xl bg-neutral-900 border border-neutral-800">
            {/* Card header */}
            <div className="px-5 py-4 border-b border-neutral-800">
              <h2 className="text-sm font-semibold">
                {step === 1 && "Details"}
                {step === 2 && "Branding"}
                {step === 3 && "Visibility & publish"}
              </h2>
            </div>

            {/* Card body */}
            <div className="px-5 py-4 space-y-6 text-sm">
              {/* STEP 1 – DETAILS */}
              {step === 1 && (
                <>
                  {/* upload type toggle */}
                  <div className="flex flex-wrap gap-3">
                    <button
                      type="button"
                      onClick={() => setSelect(0)}
                      className={`cursor-pointer px-3 py-1.5 rounded-full text-sm font-semibold ${
                        select === 0
                          ? "bg-white text-black"
                          : "bg-neutral-800 hover:bg-neutral-700"
                      }`}
                    >
                      Video file
                    </button>
                    <button
                      type="button"
                      onClick={() => setSelect(1)}
                      className={`cursor-pointer px-3 py-1.5 rounded-full text-sm font-semibold ${
                        select === 1
                          ? "bg-white text-black"
                          : "bg-neutral-800 hover:bg-neutral-700"
                      }`}
                    >
                      Stream link
                    </button>
                  </div>

                  {/* NEW: is this a short? */}
                  {select === 0 && (
                  <div className="mt-4 space-y-1">
                    <label className="text-sm font-semibold">
                      Is this a short?
                    </label>
                    <div className="flex gap-3 my-2">
                                              <button
                        type="button"
                        onClick={() => setIsShort("yes")}
                        className={`cursor-pointer px-3 py-1.5 rounded-full text-sm font-semibold ${
                          isShort === "yes"
                            ? "bg-white text-black"
                            : "bg-neutral-800 hover:bg-neutral-700"
                        }`}
                      >
                        Yes
                      </button>
                      <button
                        type="button"
                        onClick={() => setIsShort("no")}
                        className={`cursor-pointer px-3 py-1.5 rounded-full text-sm font-semibold ${
                          isShort === "no"
                            ? "bg-white text-black"
                            : "bg-neutral-800 hover:bg-neutral-700"
                        }`}
                      >
                        No
                      </button>
                    </div>
                    <p className="text-xs text-neutral-400">
                      Celips Shorts are usually vertical clips under 60 seconds.
                    </p>
                  </div>
                  )}

                  {/* Title */}
                  <div className="space-y-1">
                    <label className="text-sm font-semibold">
                      Title (required)
                    </label>
                    <input
                      type="text"
                      value={title}
                      onChange={(e) => setTitle(e.target.value)}
                      className="mt-2 w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                      placeholder="Add a title that describes your video"
                    />
                  </div>

                  {/* Description */}
                  <div className="space-y-1">
                    <label className="text-sm font-semibold">Description</label>
                    <textarea
                      rows={4}
                      value={description}
                      onChange={(e) => setDescription(e.target.value)}
                      className="mt-2 w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                      placeholder="Tell viewers about your video"
                    />
                  </div>

                  {/* file / stream area */}
                  {select === 0 ? (
                    <div className="space-y-2">
                      <label className="text-sm font-semibold">
                        Video file (required)
                      </label>
                      <label className="mt-2 flex flex-col items-center justify-center w-full h-40 border border-dashed border-neutral-700 rounded-lg cursor-pointer bg-neutral-950 hover:bg-neutral-900">
                        <input
                          type="file"
                          accept="video/mp4"
                          className="hidden"
                          onChange={handleVideoChange}
                        />
                        {!videoFileName ? (
                          <>
                            <svg
                              className="w-8 h-8 mb-3"
                              xmlns="http://www.w3.org/2000/svg"
                              viewBox="0 0 20 16"
                              fill="none"
                              aria-hidden="true"
                            >
                              <path
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                d="M13 13h3a3 3 0 000-6h-.025A5.56 5.56 0 0016 6.5 5.5 5.5 0 005.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 000 8h2.167M10 15V6m0 0L8 8m2-2 2 2"
                              />
                            </svg>
                            <p className="text-sm">
                              <span className="font-semibold">
                                Click to upload
                              </span>{" "}
                              or drag and drop
                            </p>
                            <p className="text-xs text-neutral-400 mt-1">
                              MP4 • Max ~1GB
                            </p>
                          </>
                        ) : (
                          <p className="text-sm font-medium truncate px-4">
                            {videoFileName}
                          </p>
                        )}
                      </label>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      <div className="space-y-2">
                        <label className="text-sm font-semibold">
                          Stream link (required)
                        </label>
                        <input
                          type="text"
                          value={streamLink}
                          onChange={(e) => setStreamLink(e.target.value)}
                          className="mt-2 w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                        />
                      </div>
                      <div className="space-y-2">
                        <label className="text-sm font-semibold mr-2">
                          Stream end time
                        </label>
                        <DatePicker
                          selected={datetime}
                          onChange={(date) => setDatetime(date)}
                          minDate={new Date()}
                          maxDate={
                            currentHour + 4 > 29 ? new Date() + 1 : new Date()
                          }
                          minTime={
                            new Date(
                              new Date().setHours(
                                currentHour,
                                currentMins,
                                0,
                                0
                              )
                            )
                          }
                          maxTime={
                            new Date(
                              new Date().setHours(
                                currentHour + 4,
                                currentMins,
                                0,
                                0
                              )
                            )
                          }
                          showTimeSelect
                          timeFormat="HH:mm"
                          dateFormat="dd/MM/yyyy HH:mm"
                          className="w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                        />
                        {/* <DatePicker
                          selected={datetime}
                          onChange={(date) => date && setDatetime(date)}
                          showTimeSelect
                          timeFormat="HH:mm"
                          dateFormat="dd/MM/yyyy HH:mm"
                          minDate={new Date()}
                          className="w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                        /> */}
                        <p className="text-xs text-neutral-400">
                          End time can’t be more than ~4 hours from start.
                        </p>
                      </div>
                    </div>
                  )}
                </>
              )}

              {/* STEP 2 – BRANDING (thumbnail, channel, category, tags) */}
              {step === 2 && (
                <div className="text-sm text-neutral-300 space-y-5">
                  {/* Thumbnail */}
                  <div className="space-y-2">
                    <label className="text-sm font-semibold">Thumbnail</label>
                    <p className="text-xs text-neutral-400">
                      Upload and crop a custom thumbnail (16:9), or pick one of
                      the automatically generated frames.
                    </p>

                    {/* custom upload + cropper */}
                    <div className="flex flex-col gap-3">
                      <label className="inline-flex items-center px-3 py-2 bg-neutral-950 rounded-md border border-neutral-700 cursor-pointer text-sm font-semibold hover:bg-neutral-900 w-max">
                        <input
                          type="file"
                          accept="image/png,image/jpeg,image/webp"
                          className="hidden"
                          onChange={handleThumbFileChange}
                        />
                        Upload thumbnail
                        {thumbFileName && (
                          <span className="ml-3 text-xs text-neutral-300 truncate max-w-[180px]">
                            {thumbFileName}
                          </span>
                        )}
                      </label>

                      {showCropper && rawThumbImage && (
                        <div className="mt-2 space-y-2">
                          <div className="w-full max-w-xl border border-neutral-700 rounded-md overflow-hidden bg-neutral-950">
                            <Cropper
                              ref={cropperRef}
                              style={{ width: "100%", height: 260 }}
                              src={rawThumbImage}
                              aspectRatio={16 / 9}
                              viewMode={1}
                              background={false}
                              guides
                              zoomable
                              movable
                              responsive
                              dragMode="move"
                            />
                          </div>
                          <div className="flex gap-2">
                            <button
                              type="button"
                              className="cursor-pointer px-3 py-1.5 rounded-full bg-red-700 hover:bg-red-600 text-xs font-semibold"
                              onClick={applyCrop}
                            >
                              Apply crop
                            </button>
                            <button
                              type="button"
                              className="cursor-pointer px-3 py-1.5 rounded-full border border-neutral-700 text-xs"
                              onClick={() => setShowCropper(false)}
                            >
                              Cancel
                            </button>
                          </div>
                        </div>
                      )}
                    </div>

                    {/* auto-generated thumbnails */}
                    {generatedThumbs.length > 0 && (
                      <div className="mt-4 space-y-2">
                        <p className="text-xs text-neutral-400">
                          Suggested thumbnails
                        </p>
                        <div className="flex flex-wrap gap-3">
                          {generatedThumbs.map((thumb, idx) => {
                            const selected = thumbDataUrl === thumb;
                            return (
                              <button
                                key={idx}
                                type="button"
                                onClick={() => setThumbDataUrl(thumb)}
                                className={`relative w-32 aspect-video rounded-md overflow-hidden border ${
                                  selected
                                    ? "border-red-500 ring-2 ring-red-500/60"
                                    : "border-neutral-700 hover:border-neutral-500"
                                }`}
                              >
                                {/* eslint-disable-next-line @next/next/no-img-element */}
                                <img
                                  src={thumb}
                                  alt={`Suggested thumbnail ${idx + 1}`}
                                  className="w-full h-full object-cover"
                                />
                              </button>
                            );
                          })}
                        </div>
                      </div>
                    )}

                    {/* current thumbnail preview */}
                    {thumbDataUrl && (
                      <div className="mt-4">
                        <p className="text-xs text-neutral-400 mb-1">
                          Selected thumbnail
                        </p>
                        <div className="w-40 h-24 rounded-md overflow-hidden border border-neutral-700 bg-neutral-950">
                          {/* eslint-disable-next-line @next/next/no-img-element */}
                          <img
                            src={thumbDataUrl}
                            alt="Thumbnail preview"
                            className="w-full h-full object-cover"
                          />
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Channel + Category */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2 border-t border-neutral-800">
                    <div className="space-y-1">
                      <label className="text-sm font-semibold">Channel</label>
                      <select
                        className="mt-2 w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                        value={channelId}
                        onChange={(e) => setChannelId(e.target.value)}
                      >
                        {channels.map((c) => (
                          <option key={c.id} value={c.id}>
                            {c.channel}
                          </option>
                        ))}
                      </select>
                    </div>

                    {categories.length > 0 && (
                      <div className="space-y-1">
                        <label className="text-sm font-semibold">
                          Category
                        </label>
                        <select
                          className="mt-2 w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                          value={categoryId}
                          onChange={(e) => setCategoryId(e.target.value)}
                        >
                          {categories.map((cat) => (
                            <option key={cat.id} value={cat.id}>
                              {cat.title}
                            </option>
                          ))}
                        </select>
                      </div>
                    )}
                  </div>

                  {/* Tags */}
                  <div className="space-y-1">
                    <label className="text-sm font-semibold">
                      Video tags{" "}
                      <span className="text-[10px] text-neutral-400">
                        (comma separated)
                      </span>
                    </label>
                    <input
                      type="text"
                      value={tags}
                      onChange={(e) => setTags(e.target.value)}
                      className="mt-2 w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                      placeholder="e.g. faith, worship, inspiration"
                    />
                  </div>
                </div>
              )}

              {/* STEP 3 – Visibility */}
              {step === 3 && (
                <div className="space-y-4">
                  <div className="space-y-1">
                    <label className="text-sm font-semibold">Visibility</label>
                    <select
                      className="mt-2 w-full rounded-md bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-red-600"
                      value={privacy}
                      onChange={handlePrivacyChange}
                    >
                      {privacyTypes2.map((p) => (
                        <option key={p.title} value={p.title}>
                          {p.title === "public" ? "Public" : "Private"}
                        </option>
                      ))}
                    </select>
                    <p className="text-xs text-neutral-400">
                      {privacy === "public"
                        ? "Anyone can search for and view."
                        : "Only you can view this video."}
                    </p>
                  </div>

                  <div className="space-y-2 pt-2 border-t border-neutral-800">
                    <label className="text-sm font-semibold">
                      Summary before publishing
                    </label>
                    <ul className="text-sm mt-3 text-neutral-300 list-disc list-inside space-y-1">
                      <li>Title: {title || "No title yet"}</li>
                      <li>
                        Channel:{" "}
                        {selectedChannel
                          ? selectedChannel.channel
                          : "Not selected"}
                      </li>
                      <li>
                        Upload type:{" "}
                        {select === 0 ? "Video file" : "Stream link"}
                      </li>
                      <li>
                        Visibility:{" "}
                        {privacy === "public" ? "Public" : "Private"}
                      </li>
                    </ul>
                  </div>
                </div>
              )}
            </div>
          </section>

          {/* RIGHT: preview & upload status panel */}
          <aside className="space-y-4">
            <div className="rounded-xl bg-neutral-900 border border-neutral-800 p-4 space-y-3 text-sm">
              <p className="text-xs text-neutral-400 uppercase tracking-wide">
                Upload preview
              </p>

              <div className="w-full aspect-video rounded-md bg-neutral-950 border border-neutral-800 overflow-hidden flex items-center justify-center text-xs text-neutral-500">
                {thumbDataUrl ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={thumbDataUrl}
                    alt="Current thumbnail"
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <span>No thumbnail selected</span>
                )}
              </div>

              <div className="space-y-1">
                <p className="text-xs text-neutral-400">
                  Filename:{" "}
                  <span className="text-neutral-200 font-medium">
                    {videoFileName || "—"}
                  </span>
                </p>
                <p className="text-xs text-neutral-400">
                  Video link:{" "}
                  {progress > 0 ? (
                    <span className="text-blue-400">
                      Will be available after processing
                    </span>
                  ) : (
                    <span className="text-neutral-500">Not yet available</span>
                  )}
                </p>
              </div>

              <div className="space-y-1 pt-1">
                <div className="w-full h-1.5 rounded bg-neutral-800 overflow-hidden">
                  <div
                    className="h-1.5 bg-red-600 rounded"
                    style={{ width: `${progress}%` }}
                  />
                </div>
                <p className="text-xs text-neutral-300">
                  {progress}% {progress === 0 && "• Waiting to start"}
                  {progress > 0 && progress < 100 && "• Uploading video…"}
                  {progress === 100 && "• Uploaded • Processing on server"}
                </p>
              </div>
            </div>
          </aside>
        </div>

        {/* error message */}
        {error && <div className="mt-4 text-sm text-red-400">{error}</div>}
      </div>

      {/* sticky bottom bar like YouTube */}
      <div className="fixed z-[999999] bottom-0 left-0 right-0 border-t border-neutral-800 bg-neutral-950/95 backdrop-blur-sm">
        <div className="max-w-6xl mx-auto px-4 sm:px-8 py-3 flex items-center justify-between gap-4 text-sm text-neutral-200">
          {/* left: tiny progress + hint */}
          <div className="flex items-center gap-3 flex-1">
            <div className="w-full h-2 rounded bg-neutral-800 overflow-hidden">
              <div
                className="h-2 bg-red-600 rounded"
                style={{ width: `${progress}%` }}
              />
            </div>
            <span className="whitespace-nowrap">{progress}% uploaded</span>
          </div>

          {/* right: navigation + publish */}
          <div className="flex items-center gap-3">
            {step > 1 && (
              <button
                type="button"
                onClick={prevStep}
                className="cursor-pointer px-4 py-1.5 rounded-full border border-neutral-700 hover:bg-neutral-900"
              >
                Back
              </button>
            )}

            {step < 3 && (
              <button
                type="button"
                onClick={nextStep}
                className="w-16 cursor-pointer px-4 py-1.5 rounded-full bg-neutral-800 hover:bg-neutral-700"
              >
                Next
              </button>
            )}

            {step === 3 && (
              <button
                type="button"
                disabled={uploading}
                onClick={upload}
                className={`cursor-pointer px-5 py-1.5 rounded-full font-semibold ${
                  uploading
                    ? "bg-red-900 cursor-not-allowed"
                    : "bg-red-700 hover:bg-red-600"
                }`}
              >
                {uploadButtonLabel}
              </button>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
